### ISSUE TITLE
PySide6 Bug / Error

### ISSUE THREAD

**Issue by j70141** [seanwu1105/vscode-qt-for-python#321]
I had recently installed PySide6 on my machine when it started giving me error.  So I uninstalled PySide6, and still got some errors.

I tried uninstalling the Qt for Python extension and reinstalling (after restart) and still got the errors.

I went into the extensions of VS Code and deleted the Qt for Python manually, then reinstalled, and I still got the errors.

Here is the Traceback:
Traceback (most recent call last):
  File "c:\Users\steves\.vscode\extensions\seanwu.vscode-qt-for-python-7.6.0\python\scripts\rcc.py", line 17, in <module>
    from PySide6.scripts.pyside_tool import rcc
ModuleNotFoundError: No module named 'PySide6.scripts.pyside_tool'

Command failed: C:\Python312\python.exe c:\Users\steves\.vscode\extensions\seanwu.vscode-qt-for-python-7.6.0\python\scripts\rcc.py -o c:\Users\steves\Documents\Code\Python\_samples\quickpdfviewer\viewer_rc.py c:\Users\steves\Documents\Code\Python\_samples\quickpdfviewer\viewer.qrc
Traceback (most recent call last):
  File "c:\Users\steves\.vscode\extensions\seanwu.vscode-qt-for-python-7.6.0\python\scripts\rcc.py", line 17, in <module>
    from PySide6.scripts.pyside_tool import rcc
ModuleNotFoundError: No module named 'PySide6.scripts.pyside_tool'

**Comment by kinesis19** [comment]
Hello, I have the same Error too T.T

**Comment by coderedart** [comment]
anyone know a workaround for this?
